_welcome:
    pattern:  /
    defaults: { _controller: PicweekMainBundle:Default:Index }

_error:
    pattern:  /error
    defaults: { _controller: PicweekMainBundle:Error:Error }

_place:
    resource: "@PicweekMainBundle/Controller/PlaceController.php"
    type:     annotation
    prefix:   /place

_user:
    resource: "@PicweekMainBundle/Controller/UserController.php"
    type:     annotation
    prefix:   /user


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
